# Generated by Django 4.1.1 on 2022-09-08 14:12

from django.db import migrations, models
import tgbot.core


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='group',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default=tgbot.core.Group['C'], max_length=1),
        ),
    ]
