name: Build
on: push

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Linting
        run: |
          pip install poetry pre-commit
          make generate_requirements
          git diff app/requirements.txt
#          make format
  pytest:
    name: test
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run pytest
        run: |
          poetry run pytest app -s --cov=app --cov-config=app/.coveragerc --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
  deploy:
    name: deploy
    needs: pytest
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@master
      - uses: goodsmileduck/yandex-serverless-action@v1
        with:
          token: ${{ secrets.YC_TOKEN }}
          function_id: ${{ secrets.YC_FUNCTION_ID }}
          service_account: ${{ secrets.YC_SERVICE_ACCOUNT }}
          runtime: 'python39'
          memory: '128'
          execution_timeout: "20"
          entrypoint: 'manage.handler'
          environment: SECRET_KEY=${{ secrets.SECRET_KEY }},TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }},TELEGRAM_ID=${{ secrets.TELEGRAM_ID }},DATABASE_HOST=${{ secrets.DATABASE_HOST }},DATABASE_PORT=${{ secrets.DATABASE_PORT }},DATABASE_NAME=${{ secrets.DATABASE_NAME }},DATABASE_USER=${{ secrets.DATABASE_USER }}
          source: 'app'
      - name: Set up Telegram Webhook
        run: |
          curl -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/setWebhook?url=https://functions.yandexcloud.net/${{ secrets.YC_FUNCTION_ID }}
